### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by aasseman** [hopeyen/indexer-service-rs#2]

**Comment by aasseman** [comment]
I'd think that Apache-2 makes the most sense, to be easily compatible with the rest of the indexer software, and keep with the graph's tradition.

**Comment by hopeyen** [comment]
Yes I think we can go ahead with this!
https://github.com/hopeyen/indexer-service-rs/pull/13

**Comment by aasseman** [comment]
Fixed in #13
